In [7]:
import numpy as np
import tensorflow as tf

print(tf.__version__)

2.9.2


# Introduction to tensors (creating tensors)

## Create tensors with `tf.constant`

In [2]:
# Create a scalar (rank 0 tensor)
scalar = tf.constant(21)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=21>

In [3]:
# dimension of scalar
scalar.ndim

0

In [5]:
# Create a vector
vector = tf.constant([-1, 4.15])
vector

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([-1.  ,  4.15], dtype=float32)>

In [6]:
# dim of vect
vector.ndim

1

In [8]:
# Create a Matrix
m = np.array([
    [12, 1, 0],
    [5, 4, -1]
])
mat = tf.constant(m)
mat

<tf.Tensor: shape=(2, 3), dtype=int64, numpy=
array([[12,  1,  0],
       [ 5,  4, -1]])>

In [10]:
mat.ndim

2

In [14]:
m = np.array([
    [[12, 1, 0],
    [5, 4, -1],
    [0, 5, -2]],
    [[0, 1, 3],
     [4, 5, 1],
     [-1, 2, -1]]
])

mat = tf.constant(m, dtype=tf.int8)
mat

<tf.Tensor: shape=(2, 3, 3), dtype=int8, numpy=
array([[[12,  1,  0],
        [ 5,  4, -1],
        [ 0,  5, -2]],

       [[ 0,  1,  3],
        [ 4,  5,  1],
        [-1,  2, -1]]], dtype=int8)>

In [13]:
mat.ndim

3