In [35]:
import numpy as np
import tensorflow as tf

print(tf.__version__)

2.9.2


# Introduction to tensors (creating tensors)

## Create tensors with `tf.constant`

In [36]:
# Create a scalar (rank 0 tensor)
scalar = tf.constant(21)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=21>

In [37]:
# dimension of scalar
scalar.ndim

0

In [38]:
# Create a vector
vector = tf.constant([-1, 4.15])
vector

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([-1.  ,  4.15], dtype=float32)>

In [39]:
# dim of vect
vector.ndim

1

In [40]:
# Create a Matrix
m = np.array([
    [12, 1, 0],
    [5, 4, -1]
])
mat = tf.constant(m)
mat

<tf.Tensor: shape=(2, 3), dtype=int64, numpy=
array([[12,  1,  0],
       [ 5,  4, -1]])>

In [41]:
mat.ndim

2

In [42]:
m = np.array([
    [[12, 1, 0],
    [5, 4, -1],
    [0, 5, -2]],
    [[0, 1, 3],
     [4, 5, 1],
     [-1, 2, -1]]
])

mat = tf.constant(m, dtype=tf.int8)
mat

<tf.Tensor: shape=(2, 3, 3), dtype=int8, numpy=
array([[[12,  1,  0],
        [ 5,  4, -1],
        [ 0,  5, -2]],

       [[ 0,  1,  3],
        [ 4,  5,  1],
        [-1,  2, -1]]], dtype=int8)>

In [43]:
mat.ndim

3

## Create tensors with `tf.Variable`

You can also (although you likely rarely will, because often, when working with data, tensors are created for you automatically) create tensors using `tf.Variable()`.


The difference between `tf.Variable()` and `tf.constant()` is tensors created with `tf.constant()` are **immutable** (can't be changed, can only be used to create a new tensor), where as, tensors created with `tf.Variable()` are **mutable** (can be changed).

In [44]:
# Create the same tensor with tf.Variable() and tf.constant()
changeable_tensor = tf.Variable([-1, 10])
unchangeable_tensor = tf.constant([-1, 10])

changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([-1, 10], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([-1, 10], dtype=int32)>)

Now let's try to change one of the elements of the changeable tensor.

In [45]:
# Will error (requires the .assign() method)
changeable_tensor[-1] = 1
changeable_tensor

TypeError: ignored

In [46]:
changeable_tensor[-1].assign(1)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([-1,  1], dtype=int32)>



Now let's try to change a value in a tf.constant() tensor.

In [47]:
# Will error (can't change tf.constant())
unchangeable_tensor[0].assign(10)
unchangeable_tensor

AttributeError: ignored



Which one should you use? `tf.constant()` or `tf.Variable()`?

It will depend on what your problem requires. However, most of the time, TensorFlow will automatically choose for you (when loading data or modelling data).


## Creating random tensors

We can create random tensors by using the `tf.random.Generator` class.

In [48]:
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(2, 5))

random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(2, 5))

random_1, random_2, random_1 == random_2, random_1 is random_2

(<tf.Tensor: shape=(2, 5), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702,  0.07595026, -1.2573844 , -0.23193763],
        [-1.8107855 ,  0.09988727, -0.50998646, -0.7535805 , -0.57166284]],
       dtype=float32)>, <tf.Tensor: shape=(2, 5), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702,  0.07595026, -1.2573844 , -0.23193763],
        [-1.8107855 ,  0.09988727, -0.50998646, -0.7535805 , -0.57166284]],
       dtype=float32)>, <tf.Tensor: shape=(2, 5), dtype=bool, numpy=
 array([[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]])>, False)

In [49]:
id(random_1), id(random_2)

(140309043525392, 140309043526544)

## Shuffle

In [50]:
d = np.arange(20, 26).reshape(3, 2)
# Shuffle a tensor (valuable for when you want to shuffle your data)
not_shuffled = tf.constant(d)
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int64, numpy=
array([[20, 21],
       [22, 23],
       [24, 25]])>

In [51]:
# Gets different results each time
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int64, numpy=
array([[20, 21],
       [24, 25],
       [22, 23]])>

In [52]:
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int64, numpy=
array([[22, 23],
       [20, 21],
       [24, 25]])>

In [53]:
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int64, numpy=
array([[20, 21],
       [22, 23],
       [24, 25]])>

In [54]:
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int64, numpy=
array([[20, 21],
       [22, 23],
       [24, 25]])>

In [55]:
# Shuffle in the same order every time using the seed parameter 
# (won't acutally be the same)
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int64, numpy=
array([[22, 23],
       [24, 25],
       [20, 21]])>

In [57]:
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int64, numpy=
array([[20, 21],
       [24, 25],
       [22, 23]])>

In [58]:
# Shuffle in the same order every time

# Set the global random seed
tf.random.set_seed(42)
# Set the operation random seed
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int64, numpy=
array([[20, 21],
       [22, 23],
       [24, 25]])>


## Other ways to make tensors

Though you might rarely use these (remember, many tensor operations are done behind the scenes for you), you can use tf.ones() to create a tensor of all ones and tf.zeros() to create a tensor of all zeros.


In [63]:
tf.ones(shape=(2, 3), dtype=tf.int8)

<tf.Tensor: shape=(2, 3), dtype=int8, numpy=
array([[1, 1, 1],
       [1, 1, 1]], dtype=int8)>

In [64]:
tf.zeros(shape=(2, 3), dtype=tf.int8)

<tf.Tensor: shape=(2, 3), dtype=int8, numpy=
array([[0, 0, 0],
       [0, 0, 0]], dtype=int8)>