In [1]:
import numpy as np
import tensorflow as tf

print(tf.__version__)

2.9.2


# Introduction to tensors (creating tensors)

## Create tensors with `tf.constant`

In [ ]:
# Create a scalar (rank 0 tensor)
scalar = tf.constant(21)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=21>

In [ ]:
# dimension of scalar
scalar.ndim

0

In [ ]:
# Create a vector
vector = tf.constant([-1, 4.15])
vector

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([-1.  ,  4.15], dtype=float32)>

In [ ]:
# dim of vect
vector.ndim

1

In [ ]:
# Create a Matrix
m = np.array([
    [12, 1, 0],
    [5, 4, -1]
])
mat = tf.constant(m)
mat

<tf.Tensor: shape=(2, 3), dtype=int64, numpy=
array([[12,  1,  0],
       [ 5,  4, -1]])>

In [ ]:
mat.ndim

2

In [ ]:
m = np.array([
    [[12, 1, 0],
    [5, 4, -1],
    [0, 5, -2]],
    [[0, 1, 3],
     [4, 5, 1],
     [-1, 2, -1]]
])

mat = tf.constant(m, dtype=tf.int8)
mat

<tf.Tensor: shape=(2, 3, 3), dtype=int8, numpy=
array([[[12,  1,  0],
        [ 5,  4, -1],
        [ 0,  5, -2]],

       [[ 0,  1,  3],
        [ 4,  5,  1],
        [-1,  2, -1]]], dtype=int8)>

In [ ]:
mat.ndim

3

## Create tensors with `tf.Variable`

You can also (although you likely rarely will, because often, when working with data, tensors are created for you automatically) create tensors using `tf.Variable()`.


The difference between `tf.Variable()` and `tf.constant()` is tensors created with `tf.constant()` are **immutable** (can't be changed, can only be used to create a new tensor), where as, tensors created with `tf.Variable()` are **mutable** (can be changed).

In [ ]:
# Create the same tensor with tf.Variable() and tf.constant()
changeable_tensor = tf.Variable([-1, 10])
unchangeable_tensor = tf.constant([-1, 10])

changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([-1, 10], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([-1, 10], dtype=int32)>)

Now let's try to change one of the elements of the changeable tensor.

In [ ]:
# Will error (requires the .assign() method)
changeable_tensor[-1] = 1
changeable_tensor

TypeError: ignored

In [ ]:
changeable_tensor[-1].assign(1)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([-1,  1], dtype=int32)>



Now let's try to change a value in a tf.constant() tensor.

In [ ]:
# Will error (can't change tf.constant())
unchangeable_tensor[0].assign(10)
unchangeable_tensor

AttributeError: ignored



Which one should you use? `tf.constant()` or `tf.Variable()`?

It will depend on what your problem requires. However, most of the time, TensorFlow will automatically choose for you (when loading data or modelling data).


## Creating random tensors

We can create random tensors by using the `tf.random.Generator` class.

In [ ]:
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(2, 5))

random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(2, 5))

random_1, random_2, random_1 == random_2, random_1 is random_2

(<tf.Tensor: shape=(2, 5), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702,  0.07595026, -1.2573844 , -0.23193763],
        [-1.8107855 ,  0.09988727, -0.50998646, -0.7535805 , -0.57166284]],
       dtype=float32)>, <tf.Tensor: shape=(2, 5), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702,  0.07595026, -1.2573844 , -0.23193763],
        [-1.8107855 ,  0.09988727, -0.50998646, -0.7535805 , -0.57166284]],
       dtype=float32)>, <tf.Tensor: shape=(2, 5), dtype=bool, numpy=
 array([[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]])>, False)

In [ ]:
id(random_1), id(random_2)

(140309043525392, 140309043526544)

## Shuffle

In [ ]:
d = np.arange(20, 26).reshape(3, 2)
# Shuffle a tensor (valuable for when you want to shuffle your data)
not_shuffled = tf.constant(d)
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int64, numpy=
array([[20, 21],
       [22, 23],
       [24, 25]])>

In [ ]:
# Gets different results each time
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int64, numpy=
array([[20, 21],
       [24, 25],
       [22, 23]])>

In [ ]:
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int64, numpy=
array([[22, 23],
       [20, 21],
       [24, 25]])>

In [ ]:
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int64, numpy=
array([[20, 21],
       [22, 23],
       [24, 25]])>

In [ ]:
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int64, numpy=
array([[20, 21],
       [22, 23],
       [24, 25]])>

In [ ]:
# Shuffle in the same order every time using the seed parameter 
# (won't acutally be the same)
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int64, numpy=
array([[22, 23],
       [24, 25],
       [20, 21]])>

In [ ]:
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int64, numpy=
array([[20, 21],
       [24, 25],
       [22, 23]])>

In [ ]:
# Shuffle in the same order every time

# Set the global random seed
tf.random.set_seed(42)
# Set the operation random seed
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int64, numpy=
array([[20, 21],
       [22, 23],
       [24, 25]])>


## Other ways to make tensors

Though you might rarely use these (remember, many tensor operations are done behind the scenes for you), you can use tf.ones() to create a tensor of all ones and tf.zeros() to create a tensor of all zeros.


In [ ]:
tf.ones(shape=(2, 3), dtype=tf.int8)

<tf.Tensor: shape=(2, 3), dtype=int8, numpy=
array([[1, 1, 1],
       [1, 1, 1]], dtype=int8)>

In [ ]:
tf.zeros(shape=(2, 3), dtype=tf.int8)

<tf.Tensor: shape=(2, 3), dtype=int8, numpy=
array([[0, 0, 0],
       [0, 0, 0]], dtype=int8)>

In [ ]:
numpy_A = np.arange(1, 25, dtype=np.int32) # create a NumPy array between 1 and 25
A = tf.constant(numpy_A,  
                shape=[2, 4, 3]) # note: the shape total (2*4*3) has to match the number of elements in the array
numpy_A, A

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32),
 <tf.Tensor: shape=(2, 4, 3), dtype=int32, numpy=
 array([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]],
 
        [[13, 14, 15],
         [16, 17, 18],
         [19, 20, 21],
         [22, 23, 24]]], dtype=int32)>)

# Getting information from tensors (shape, rank, size)

In [ ]:
# Create a rank 4 tensor (4 dimensions)
rank_4_tensor = tf.random.Generator.from_seed(42)
rank_4_tensor = rank_4_tensor.normal(shape=(2, 4, 2, 3))
rank_4_tensor

<tf.Tensor: shape=(2, 4, 2, 3), dtype=float32, numpy=
array([[[[-0.7565803 , -0.06854702,  0.07595026],
         [-1.2573844 , -0.23193763, -1.8107855 ]],

        [[ 0.09988727, -0.50998646, -0.7535805 ],
         [-0.57166284,  0.1480774 , -0.23362993]],

        [[-0.3522796 ,  0.40621263, -1.0523509 ],
         [ 1.2054597 ,  1.6874489 , -0.4462975 ]],

        [[-2.3410842 ,  0.99009085, -0.0876323 ],
         [-0.635568  , -0.6161736 , -1.9441465 ]]],


       [[[-0.48293006, -0.52447474, -1.0345329 ],
         [ 1.3066901 , -1.5184573 , -0.4585211 ]],

        [[ 0.5714663 , -1.5331722 ,  0.45331386],
         [ 1.1487608 , -1.2659091 , -0.47450137]],

        [[ 2.006022  ,  0.28288034, -0.30288252],
         [-1.443651  ,  1.0034493 ,  0.20857747]],

        [[ 0.35700995,  1.0648885 ,  1.2432485 ],
         [-2.2173238 ,  0.18706243,  0.6617961 ]]]], dtype=float32)>

In [ ]:
def infos(tensor):
  print("Datatype of every element:", tensor.dtype)
  print("Number of dimensions (rank):", tensor.ndim)
  print("Shape of tensor:", tensor.shape)
  print("Elements along axis 0 of tensor:", tensor.shape[0])
  print("Elements along last axis of tensor:", tensor.shape[-1])
  print("Total number of elements (2*4*2*3):", tf.size(tensor).numpy()) # .numpy() converts to NumPy array

infos(rank_4_tensor)

Datatype of every element: <dtype: 'float32'>
Number of dimensions (rank): 4
Shape of tensor: (2, 4, 2, 3)
Elements along axis 0 of tensor: 2
Elements along last axis of tensor: 3
Total number of elements (2*4*2*3): 48


In [2]:
# Create a rank 2 tensor (2 dimensions)
rank_2_tensor = tf.constant([[10, 7],
                             [3, 4]])

# Get the last item of each row
rank_2_tensor[:, -1]


<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [3]:
# Add an extra dimension (to the end)
rank_3_tensor = rank_2_tensor[..., tf.newaxis] # in Python "..." means "all dimensions prior to"
rank_2_tensor.shape, rank_3_tensor.shape

(TensorShape([2, 2]), TensorShape([2, 2, 1]))

You can achieve the same using `tf.expand_dims()`.

In [5]:
tf.expand_dims(rank_2_tensor, axis=-1).shape.as_list()

[2, 2, 1]

# Manipulating tensors (tensor operations)

Finding patterns in tensors (numerical representation of data) requires manipulating them.

Again, when building models in TensorFlow, much of this pattern discovery is done for you.  


### Basic operations

You can perform many of the basic mathematical operations directly on tensors using Python operators such as, `+, -, *`.


In [6]:
tensor = tf.constant([[10, 7], [3, 4]])
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [7]:
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [11]:
tf.add(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [12]:
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [17]:
tf.divide(tensor, 0)

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[inf, inf],
       [inf, inf]])>


## Matrix mutliplication

One of the most common operations in machine learning algorithms is matrix multiplication.

TensorFlow implements this matrix multiplication functionality in the tf.matmul() method.

The main two rules for matrix multiplication to remember are:

  1. The inner dimensions must match:

    - (3, 5) @ (3, 5) won't work
    - (5, 3) @ (3, 5) will work
    - (3, 5) @ (5, 3) will work

  2. The resulting matrix has the shape of the outer dimensions:

    - (5, 3) @ (3, 5) -> (5, 5)
    - (3, 5) @ (5, 3) -> (3, 3)

🔑 **Note**: '@' in Python is the symbol for matrix multiplication.

