In [1]:
import numpy as np
import tensorflow as tf

print(tf.__version__)

2.9.2


# Introduction to tensors (creating tensors)

## Create tensors with `tf.constant`

In [ ]:
# Create a scalar (rank 0 tensor)
scalar = tf.constant(21)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=21>

In [ ]:
# dimension of scalar
scalar.ndim

0

In [ ]:
# Create a vector
vector = tf.constant([-1, 4.15])
vector

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([-1.  ,  4.15], dtype=float32)>

In [ ]:
# dim of vect
vector.ndim

1

In [ ]:
# Create a Matrix
m = np.array([
    [12, 1, 0],
    [5, 4, -1]
])
mat = tf.constant(m)
mat

<tf.Tensor: shape=(2, 3), dtype=int64, numpy=
array([[12,  1,  0],
       [ 5,  4, -1]])>

In [ ]:
mat.ndim

2

In [ ]:
m = np.array([
    [[12, 1, 0],
    [5, 4, -1],
    [0, 5, -2]],
    [[0, 1, 3],
     [4, 5, 1],
     [-1, 2, -1]]
])

mat = tf.constant(m, dtype=tf.int8)
mat

<tf.Tensor: shape=(2, 3, 3), dtype=int8, numpy=
array([[[12,  1,  0],
        [ 5,  4, -1],
        [ 0,  5, -2]],

       [[ 0,  1,  3],
        [ 4,  5,  1],
        [-1,  2, -1]]], dtype=int8)>

In [ ]:
mat.ndim

3

## Create tensors with `tf.Variable`

You can also (although you likely rarely will, because often, when working with data, tensors are created for you automatically) create tensors using `tf.Variable()`.


The difference between `tf.Variable()` and `tf.constant()` is tensors created with `tf.constant()` are **immutable** (can't be changed, can only be used to create a new tensor), where as, tensors created with `tf.Variable()` are **mutable** (can be changed).

In [ ]:
# Create the same tensor with tf.Variable() and tf.constant()
changeable_tensor = tf.Variable([-1, 10])
unchangeable_tensor = tf.constant([-1, 10])

changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([-1, 10], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([-1, 10], dtype=int32)>)

Now let's try to change one of the elements of the changeable tensor.

In [ ]:
# Will error (requires the .assign() method)
changeable_tensor[-1] = 1
changeable_tensor

TypeError: ignored

In [ ]:
changeable_tensor[-1].assign(1)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([-1,  1], dtype=int32)>



Now let's try to change a value in a tf.constant() tensor.

In [ ]:
# Will error (can't change tf.constant())
unchangeable_tensor[0].assign(10)
unchangeable_tensor

AttributeError: ignored



Which one should you use? `tf.constant()` or `tf.Variable()`?

It will depend on what your problem requires. However, most of the time, TensorFlow will automatically choose for you (when loading data or modelling data).


## Creating random tensors

We can create random tensors by using the `tf.random.Generator` class.

In [ ]:
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(2, 5))

random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(2, 5))

random_1, random_2, random_1 == random_2, random_1 is random_2

(<tf.Tensor: shape=(2, 5), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702,  0.07595026, -1.2573844 , -0.23193763],
        [-1.8107855 ,  0.09988727, -0.50998646, -0.7535805 , -0.57166284]],
       dtype=float32)>, <tf.Tensor: shape=(2, 5), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702,  0.07595026, -1.2573844 , -0.23193763],
        [-1.8107855 ,  0.09988727, -0.50998646, -0.7535805 , -0.57166284]],
       dtype=float32)>, <tf.Tensor: shape=(2, 5), dtype=bool, numpy=
 array([[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]])>, False)

In [ ]:
id(random_1), id(random_2)

(140309043525392, 140309043526544)

## Shuffle

In [ ]:
d = np.arange(20, 26).reshape(3, 2)
# Shuffle a tensor (valuable for when you want to shuffle your data)
not_shuffled = tf.constant(d)
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int64, numpy=
array([[20, 21],
       [22, 23],
       [24, 25]])>

In [ ]:
# Gets different results each time
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int64, numpy=
array([[20, 21],
       [24, 25],
       [22, 23]])>

In [ ]:
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int64, numpy=
array([[22, 23],
       [20, 21],
       [24, 25]])>

In [ ]:
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int64, numpy=
array([[20, 21],
       [22, 23],
       [24, 25]])>

In [ ]:
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int64, numpy=
array([[20, 21],
       [22, 23],
       [24, 25]])>

In [ ]:
# Shuffle in the same order every time using the seed parameter 
# (won't acutally be the same)
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int64, numpy=
array([[22, 23],
       [24, 25],
       [20, 21]])>

In [ ]:
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int64, numpy=
array([[20, 21],
       [24, 25],
       [22, 23]])>

In [ ]:
# Shuffle in the same order every time

# Set the global random seed
tf.random.set_seed(42)
# Set the operation random seed
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int64, numpy=
array([[20, 21],
       [22, 23],
       [24, 25]])>


## Other ways to make tensors

Though you might rarely use these (remember, many tensor operations are done behind the scenes for you), you can use tf.ones() to create a tensor of all ones and tf.zeros() to create a tensor of all zeros.


In [ ]:
tf.ones(shape=(2, 3), dtype=tf.int8)

<tf.Tensor: shape=(2, 3), dtype=int8, numpy=
array([[1, 1, 1],
       [1, 1, 1]], dtype=int8)>

In [ ]:
tf.zeros(shape=(2, 3), dtype=tf.int8)

<tf.Tensor: shape=(2, 3), dtype=int8, numpy=
array([[0, 0, 0],
       [0, 0, 0]], dtype=int8)>

In [ ]:
numpy_A = np.arange(1, 25, dtype=np.int32) # create a NumPy array between 1 and 25
A = tf.constant(numpy_A,  
                shape=[2, 4, 3]) # note: the shape total (2*4*3) has to match the number of elements in the array
numpy_A, A

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32),
 <tf.Tensor: shape=(2, 4, 3), dtype=int32, numpy=
 array([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]],
 
        [[13, 14, 15],
         [16, 17, 18],
         [19, 20, 21],
         [22, 23, 24]]], dtype=int32)>)

# Getting information from tensors (shape, rank, size)

In [ ]:
# Create a rank 4 tensor (4 dimensions)
rank_4_tensor = tf.random.Generator.from_seed(42)
rank_4_tensor = rank_4_tensor.normal(shape=(2, 4, 2, 3))
rank_4_tensor

<tf.Tensor: shape=(2, 4, 2, 3), dtype=float32, numpy=
array([[[[-0.7565803 , -0.06854702,  0.07595026],
         [-1.2573844 , -0.23193763, -1.8107855 ]],

        [[ 0.09988727, -0.50998646, -0.7535805 ],
         [-0.57166284,  0.1480774 , -0.23362993]],

        [[-0.3522796 ,  0.40621263, -1.0523509 ],
         [ 1.2054597 ,  1.6874489 , -0.4462975 ]],

        [[-2.3410842 ,  0.99009085, -0.0876323 ],
         [-0.635568  , -0.6161736 , -1.9441465 ]]],


       [[[-0.48293006, -0.52447474, -1.0345329 ],
         [ 1.3066901 , -1.5184573 , -0.4585211 ]],

        [[ 0.5714663 , -1.5331722 ,  0.45331386],
         [ 1.1487608 , -1.2659091 , -0.47450137]],

        [[ 2.006022  ,  0.28288034, -0.30288252],
         [-1.443651  ,  1.0034493 ,  0.20857747]],

        [[ 0.35700995,  1.0648885 ,  1.2432485 ],
         [-2.2173238 ,  0.18706243,  0.6617961 ]]]], dtype=float32)>

In [ ]:
def infos(tensor):
  print("Datatype of every element:", tensor.dtype)
  print("Number of dimensions (rank):", tensor.ndim)
  print("Shape of tensor:", tensor.shape)
  print("Elements along axis 0 of tensor:", tensor.shape[0])
  print("Elements along last axis of tensor:", tensor.shape[-1])
  print("Total number of elements (2*4*2*3):", tf.size(tensor).numpy()) # .numpy() converts to NumPy array

infos(rank_4_tensor)

Datatype of every element: <dtype: 'float32'>
Number of dimensions (rank): 4
Shape of tensor: (2, 4, 2, 3)
Elements along axis 0 of tensor: 2
Elements along last axis of tensor: 3
Total number of elements (2*4*2*3): 48


In [ ]:
# Create a rank 2 tensor (2 dimensions)
rank_2_tensor = tf.constant([[10, 7],
                             [3, 4]])

# Get the last item of each row
rank_2_tensor[:, -1]


<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [ ]:
# Add an extra dimension (to the end)
rank_3_tensor = rank_2_tensor[..., tf.newaxis] # in Python "..." means "all dimensions prior to"
rank_2_tensor.shape, rank_3_tensor.shape

(TensorShape([2, 2]), TensorShape([2, 2, 1]))

You can achieve the same using `tf.expand_dims()`.

In [ ]:
tf.expand_dims(rank_2_tensor, axis=-1).shape.as_list()

[2, 2, 1]

# Manipulating tensors (tensor operations)

Finding patterns in tensors (numerical representation of data) requires manipulating them.

Again, when building models in TensorFlow, much of this pattern discovery is done for you.  


### Basic operations

You can perform many of the basic mathematical operations directly on tensors using Python operators such as, `+, -, *`.


In [ ]:
tensor = tf.constant([[10, 7], [3, 4]])
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [ ]:
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [ ]:
tf.add(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [ ]:
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [ ]:
tf.divide(tensor, 0)

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[inf, inf],
       [inf, inf]])>


## Matrix mutliplication

One of the most common operations in machine learning algorithms is matrix multiplication.

TensorFlow implements this matrix multiplication functionality in the tf.matmul() method.

The main two rules for matrix multiplication to remember are:

  1. The inner dimensions must match:

    - (3, 5) @ (3, 5) won't work
    - (5, 3) @ (3, 5) will work
    - (3, 5) @ (5, 3) will work

  2. The resulting matrix has the shape of the outer dimensions:

    - (5, 3) @ (3, 5) -> (5, 5)
    - (3, 5) @ (5, 3) -> (3, 3)

🔑 **Note**: '@' in Python is the symbol for matrix multiplication.



In [ ]:
# Create (3, 2) tensor
X = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]])

# Create another (3, 2) tensor
Y = tf.constant([[7, 8],
                 [9, 10],
                 [11, 12]])
X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [ ]:
X @ tf.transpose(Y)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [ ]:
tf.transpose(X) @ Y

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [ ]:
# Perform matrix multiplication between X and Y (transposed)
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [ ]:
# Perform matrix multiplication between X and Y (reshaped)
tf.matmul(X, tf.reshape(Y, (2, 3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>


## Changing the datatype of a tensor

Sometimes you'll want to alter the default datatype of your tensor.

This is common when you want to compute using less precision (e.g. 16-bit floating point numbers vs. 32-bit floating point numbers).

Computing with less precision is useful on devices with less computing capacity such as mobile devices (because the less bits, the less space the computations require).

You can change the datatype of a tensor using `tf.cast()`.


In [2]:
X1 = tf.constant([10, 7])
X2 = tf.constant([-1.2, 5])

X1.dtype, X2.dtype

(tf.int32, tf.float32)

In [3]:
C1 = tf.cast(X1, dtype=tf.float16)
C2 = tf.cast(X2, dtype=tf.float64)

C1.dtype, C2.dtype

(tf.float16, tf.float64)

## 
Getting the absolute value

Sometimes you'll want the absolute values (all values are positive) of elements in your tensors.

To do so, you can use `tf.abs()`.


In [5]:
X = tf.constant([[7, -10, -5],[2, -2, -1]])

X, tf.abs(X)

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[  7, -10,  -5],
        [  2,  -2,  -1]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[ 7, 10,  5],
        [ 2,  2,  1]], dtype=int32)>)

## Finding the min, max, mean, sum (aggregation)

You can quickly aggregate (perform a calculation on a whole tensor) tensors to find things like the minimum value, maximum value, mean and sum of all the elements.

To do so, aggregation methods typically have the syntax `reduce_[action]()`, such as:

  - `tf.reduce_min()` - find the minimum value in a tensor.
  - `tf.reduce_max()` - find the maximum value in a tensor (helpful for when you want to find the highest prediction probability).
  - `tf.reduce_mean()` - find the mean of all elements in a tensor.
  - `tf.reduce_sum()` - find the sum of all elements in a tensor.  

**Note**: typically, each of these is under the math module, e.g. `tf.math.reduce_min()` but you can use the alias `tf.reduce_min()`.

Let's see them in action.

In [6]:
# Create a tensor with 50 random values between 0 and 100
tf.random.set_seed(42)
X = tf.constant(np.random.randint(0, 100, size=50))
X

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([ 6, 68,  5, 92, 51, 16, 49, 74, 46, 69, 28, 91, 55, 81, 27,  5, 32,
       60, 29, 37, 56,  9, 45,  3, 23, 14, 45, 46, 87, 71, 81, 54,  8, 14,
       29, 42, 10, 27, 37, 96, 29, 42, 47, 99,  1, 92, 45, 87, 74, 36])>

In [8]:
# min
tf.reduce_min(X).numpy()

1

In [9]:
# max
tf.reduce_max(X).numpy()

99

In [10]:
# mean
tf.reduce_mean(X).numpy()

45

In [11]:
# sum
tf.reduce_sum(X).numpy()

2270

In [20]:
# std, var
# tf.reduce_std(X).numpy(), 
# tf.reduce_variance(X).numpy()
tf.math.reduce_std(tf.cast(X, dtype=tf.float32)).numpy(), tf.math.reduce_variance(tf.cast(X, dtype=tf.float32)).numpy()

(28.238272, 797.4)

## Finding the positional maximum and minimum
How about finding the position a tensor where the maximum value occurs?

This is helpful when you want to line up your labels (say `['Green', 'Blue', 'Red']`) with your prediction probabilities tensor (e.g. `[0.98, 0.01, 0.01]`).

In this case, the predicted label (the one with the highest prediction probability) would be 'Green'.

You can do the same for the minimum (if required) with the following:

  - `tf.argmax()` - find the position of the maximum element in a given tensor.
  - `tf.argmin()` - find the position of the minimum element in a given tensor.



In [22]:
# Create a tensor with 50 values between 0 and 1
tf.random.set_seed(42)
X = tf.constant(np.random.random(50))
X

<tf.Tensor: shape=(50,), dtype=float64, numpy=
array([0.78879168, 0.56854168, 0.00779142, 0.12747923, 0.56622722,
       0.22132125, 0.45004091, 0.73606034, 0.93555112, 0.66087772,
       0.9770007 , 0.49125228, 0.97598242, 0.8687771 , 0.58107209,
       0.11667342, 0.08894048, 0.29174401, 0.57122794, 0.07543879,
       0.90614608, 0.62481205, 0.52343742, 0.10039582, 0.41120551,
       0.09057161, 0.0561985 , 0.17888599, 0.80622938, 0.68932113,
       0.5575878 , 0.11290822, 0.97195432, 0.55031114, 0.11571161,
       0.78504928, 0.63801887, 0.38093108, 0.08580804, 0.48206252,
       0.09889108, 0.42555295, 0.7893639 , 0.72474544, 0.2059244 ,
       0.62517019, 0.2817144 , 0.47601526, 0.26817332, 0.38943632])>

In [23]:
# argmin argmax
tf.argmin(X).numpy(), tf.argmax(X).numpy()

(2, 10)

In [27]:
X[tf.argmin(X)].numpy() == tf.reduce_min(X).numpy(), X[tf.argmax(X)].numpy() == tf.reduce_max(X).numpy()

(True, True)

## Squeezing a tensor (removing all single dimensions)

If you need to remove single-dimensions from a tensor (dimensions with size 1), you can use `tf.squeeze()`.

- `tf.squeeze()` - remove all dimensions of 1 from a tensor.



In [28]:
X = tf.constant(tf.random.normal(shape=[50]), shape=[1,1,1, 2, 25])
X

<tf.Tensor: shape=(1, 1, 1, 2, 25), dtype=float32, numpy=
array([[[[[ 0.3274685 , -0.8426258 ,  0.3194337 , -1.4075519 ,
           -2.3880599 , -1.0392479 , -0.5573232 ,  0.539707  ,
            1.6994323 ,  0.28893656, -1.5066116 , -0.26454744,
           -0.59722406, -1.9171132 , -0.62044144,  0.8504023 ,
           -0.40604794, -3.0258412 ,  0.9058464 ,  0.29855987,
           -0.22561555, -0.7616443 , -1.891714  , -0.9384712 ,
            0.77852213],
          [-0.47338897,  0.97772694,  0.24694404,  0.20573747,
           -0.5256233 ,  0.32410017,  0.02545409, -0.10638497,
           -0.6369475 ,  1.1603122 ,  0.2507359 , -0.41728497,
            0.40125778, -1.4145442 , -0.59318566, -1.6617213 ,
            0.33567193,  0.10815629,  0.2347968 , -0.56668764,
           -0.35819843,  0.88698626,  0.5274477 ,  0.70402247,
           -0.33421248]]]]], dtype=float32)>

In [31]:
tf.squeeze(X)

<tf.Tensor: shape=(2, 25), dtype=float32, numpy=
array([[ 0.3274685 , -0.8426258 ,  0.3194337 , -1.4075519 , -2.3880599 ,
        -1.0392479 , -0.5573232 ,  0.539707  ,  1.6994323 ,  0.28893656,
        -1.5066116 , -0.26454744, -0.59722406, -1.9171132 , -0.62044144,
         0.8504023 , -0.40604794, -3.0258412 ,  0.9058464 ,  0.29855987,
        -0.22561555, -0.7616443 , -1.891714  , -0.9384712 ,  0.77852213],
       [-0.47338897,  0.97772694,  0.24694404,  0.20573747, -0.5256233 ,
         0.32410017,  0.02545409, -0.10638497, -0.6369475 ,  1.1603122 ,
         0.2507359 , -0.41728497,  0.40125778, -1.4145442 , -0.59318566,
        -1.6617213 ,  0.33567193,  0.10815629,  0.2347968 , -0.56668764,
        -0.35819843,  0.88698626,  0.5274477 ,  0.70402247, -0.33421248]],
      dtype=float32)>

## One-hot encoding

If you have a tensor of indicies and would like to *one-hot encode* it, you can use `tf.one_hot()`.

You should also specify the `depth` parameter (the level which you want to *one-hot encode* to).


In [33]:
# Create a list of indices
some_list = [0, 1, 2, 3]

# One hot encode them
tf.one_hot(some_list, depth=len(some_list))

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

You can also specify values for `on_value` and `off_value` instead of the default 0 and 1.

In [34]:
# Specify custom values for on and off encoding
tf.one_hot(some_list, depth=len(some_list), on_value="Alto", off_value="Malto")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'Alto', b'Malto', b'Malto', b'Malto'],
       [b'Malto', b'Alto', b'Malto', b'Malto'],
       [b'Malto', b'Malto', b'Alto', b'Malto'],
       [b'Malto', b'Malto', b'Malto', b'Alto']], dtype=object)>