In [5]:
import tensorflow as tf
import numpy as np


print(tf.__version__)

2.10.0


# 1. Create a vector, scalar, matrix and tensor with values of your choosing using `tf.constant()`.

## Verctor

In [2]:
tf.random.set_seed(42)
vector = tf.constant(tf.random.normal([3], 10, 40, dtype=tf.float32))
vector

2022-12-03 10:14:52.201817: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


<tf.Tensor: shape=(3,), dtype=float32, numpy=array([ 23.09874 , -23.705032,  22.777348], dtype=float32)>

## Scalar

In [3]:
scalar = tf.constant([10], dtype=tf.float32)
scalar

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([10.], dtype=float32)>

## Matrix

In [6]:
matrix = tf.constant(np.arange(0, 10).reshape(2, 5), dtype=tf.float32)
matrix

<tf.Tensor: shape=(2, 5), dtype=float32, numpy=
array([[0., 1., 2., 3., 4.],
       [5., 6., 7., 8., 9.]], dtype=float32)>

## Tensor

In [11]:
tf.random.set_seed(42)
tensor = tf.constant(tf.random.normal([150, 150, 3], 0, 1, dtype=tf.float32))
tensor

<tf.Tensor: shape=(150, 150, 3), dtype=float32, numpy=
array([[[ 3.27468514e-01, -8.42625797e-01,  3.19433689e-01],
        [-1.40755188e+00, -2.38805985e+00, -1.03924787e+00],
        [-5.57323217e-01,  5.39707005e-01,  1.69943225e+00],
        ...,
        [ 9.34684873e-02,  4.64972824e-01, -1.36276677e-01],
        [ 1.95608902e+00,  1.33834195e+00, -1.66000390e+00],
        [ 5.86475611e-01, -4.42954361e-01, -1.41154170e-01]],

       [[-2.09318233e+00,  8.33342791e-01,  8.95059109e-01],
        [-1.28661513e+00, -6.66700542e-01,  1.59461153e+00],
        [-7.55213678e-01, -6.30860865e-01,  2.24478078e+00],
        ...,
        [ 1.69578862e+00,  7.40815327e-02, -8.82063448e-01],
        [-5.82517311e-03, -2.61725575e-01,  7.83099353e-01],
        [ 1.74183771e-01,  9.49244946e-03,  2.07736522e-01]],

       [[-6.69199169e-01, -3.93965244e-01, -2.24405956e+00],
        [-2.15216398e-01,  4.34078664e-01, -4.06771898e-01],
        [-8.01864743e-01,  1.32630324e+00,  3.00820976e-01],


# 2. Find the shape, rank and size of the tensors you created in 1.

In [12]:
def tensor_info(tensor):
    print(f"Tensor shape: {tensor.shape}")
    print(f"Tensor rank: {tensor.ndim}")
    print(f"Tensor size: {tf.size(tensor).numpy()}")

In [13]:
tensor_info(tensor)

Tensor shape: (150, 150, 3)
Tensor rank: 3
Tensor size: 67500


# 3. Create two tensors containing random values between 0 and 1 with shape [5, 300].

In [14]:
t1 = tf.constant(tf.random.normal([5, 300], 0, 1, dtype=tf.float32))
t2 = tf.constant(tf.random.normal([5, 300], 0, 1, dtype=tf.float32))

# 4. Multiply the two tensors you created in 3 using matrix multiplication.

In [15]:
t1.shape, t2.shape

(TensorShape([5, 300]), TensorShape([5, 300]))

In [44]:
t = tf.linalg.matmul(t1 , tf.transpose(t2))

In [45]:
t.shape

TensorShape([5, 5])

# 5. Multiply the two tensors you created in 3 using dot product.

In [20]:
t1 @ tf.transpose(t2)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[-19.700884  ,   1.9933591 ,  -7.9026895 ,  19.950592  ,
        -19.12231   ],
       [ -6.053338  ,  12.419187  ,  22.246252  ,  20.912073  ,
          6.4155645 ],
       [  9.499852  ,  -2.3097072 ,   7.6603155 , -12.769199  ,
          2.4743052 ],
       [ 17.098806  ,  11.836251  , -15.267178  ,   0.79975617,
        -10.531874  ],
       [  9.994848  ,  45.667328  ,  13.350237  , -28.35382   ,
          8.682099  ]], dtype=float32)>

# 6. Create a tensor with random values between 0 and 1 with shape [224, 224, 3].

In [22]:
tensor = tf.constant(tf.random.normal([224, 224, 3], 0, 1, dtype=tf.float32))

# 7. Find the min and max values of the tensor you created in 6.

In [23]:
tf.math.reduce_min(tensor).numpy(), tf.math.reduce_max(tensor).numpy()

(-4.5823126, 4.118299)

# 8. Created a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3].

In [24]:
tf.random.set_seed(42)
tensor = tf.constant(tf.random.uniform([1, 224, 224, 3], dtype=tf.float32))

In [25]:
tensor.shape

TensorShape([1, 224, 224, 3])

In [26]:
tensor_squeeze = tf.squeeze(tensor)
tensor_squeeze.shape

TensorShape([224, 224, 3])

# 9. Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.

In [67]:
tf.random.set_seed(2)
tensor = tf.constant(tf.random.normal([10], 10, 100, dtype=tf.float32))
tensor = tf.math.abs(tensor)
tensor

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([ 53.616886 , 180.93794  , 147.89066  ,  94.05852  ,   9.904416 ,
        26.947803 , 101.5631   ,  65.12486  ,   3.4969864,   3.7946577],
      dtype=float32)>

In [68]:
tf.math.argmin(tensor).numpy(), tf.math.argmax(tensor).numpy()

(8, 1)

# 10. One-hot encode the tensor you created in 9.

In [69]:
tf.one_hot(indices=tf.cast(tensor.numpy(), dtype=tf.int32), depth=10)

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [54]:
ten_tensor = tf.constant([0 ,1 ,2 ,3, 4, 9, 10, 0.1 , -000.1 , 6])
tf.one_hot(indices=tf.cast(ten_tensor.numpy(), dtype=tf.int32), depth=10)

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.]], dtype=float32)>

In [56]:
ten_tensor, tensor

(<tf.Tensor: shape=(10,), dtype=float32, numpy=
 array([ 0. ,  1. ,  2. ,  3. ,  4. ,  9. , 10. ,  0.1, -0.1,  6. ],
       dtype=float32)>,
 <tf.Tensor: shape=(10,), dtype=float32, numpy=
 array([63.10183  , 38.510746 , 28.817074 , 41.09308  , -6.2973547,
        65.31396  , 71.41292  , 85.968895 , 14.895899 , 14.551655 ],
       dtype=float32)>)